{% set version = "0.4-0.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-npsurv
  version: {{ version|replace("-", "_") }}

source:
  fn: npsurv_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/npsurv_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/npsurv/npsurv_{{ version }}.tar.gz
  sha256: 085dee4e6ed6d4340ced8fee841d807e4f77e657f681ce30dae9ae91ee8add26

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-lsei
  run:
    - r-base
    - r-lsei

test:
  commands:
    - $R -e "library('npsurv')"           # [not win]
    - "\"%R%\" -e \"library('npsurv')\""  # [win]

about:
  home: https://www.stat.auckland.ac.nz/~yongwang
  license: GPL (>= 2)
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
  summary: 'Contains functions for non-parametric survival analysis of exact and interval-censored observations. '
  license_family: GPL3

extra:
  recipe-maintainers:
    - conda-forge/r
