appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: mkFfTMaBgQXhLq2tL5PDsSs6zxjGOabXRM8WWiCyAbK7sq2KqB/VTKR2kLup4HBVJv8vuYIhL3b9nr4l3KNwRAeG2m8kNHdTJ2YMzDDD4ISHDV1i9fvddC4KAx2XqF+EuSC1jDQaF/S3FMRh/XTwOLUo/FpJL+AhvozCK3dA5hUZef8KYrRL72+Z/Gq31yKHIyIBOH6UrbjTKjSxx8IrLofuN8T1BAqujxfiE+PsNd54thNvoMK0wLyvFAm86WEIB40fMdU9zfGLb+bk6Cn47036EmMkBmNmLQUAcTzqbUGZeT8Kz23N4xSZhf1sTlG3+TSxjtW6r9TzU0+RKvxfZxrTa102oxu/xvQkowkoV1/MIbJqiJlZCm0Nrvp81yMbuM+1R0Mp5HWLZG3evFLYIUN3zzxvNDimxmG6kW5TMFyQFTt9iq03XPtZ6hg/AgL8YRPcZwpk7/4SpVaB+8LhSLOPoEDR3u+mx3Mwul39plRFtkPhXArCcpQG9WB6I1DwUe75y9F7HRMM2uHTug1HB9VISoYyPACH8eG43YasOG630HtYRoSc1olSTv9KC0JSsubKwkDyUKgUrCkllA+pmmmegsgKKHzxD5SLzU6kHDSOo5in235Nu967dEmvrmRIxPK7GgxJDPdaGOuBZWv/7gz18gInysneHJ+NaXcZR8c=}
